# -*- coding: utf-8 -*-
"""Diwali_Sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16A_LYntXv973j8RPerX9-NUNMnGEFNoF
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

data = pd.read_csv('Diwali_Sales_Data_Initial.csv', encoding='latin1')
data.shape

data.head(3)

data.info()

data.drop(['Status','unnamed1'], axis=1, inplace=True)

pd.isnull(data)

pd.isnull(data).sum()

data.shape

data.dropna(inplace=True) #inplace used to save the changes

data.shape

data['Amount'] = data['Amount'].astype('int')

data['Amount'].dtypes

data.columns

data.rename(columns={'Marital_Status':'Shaadi'})

data.describe()

data[['Age','Orders','Amount']].describe()

"""# Exploratory Data Analysis

##Gender
"""

k = sns.countplot(x='Gender',data = data)
for bars in k.containers:
  k.bar_label(bars)

sales = data.groupby(['Gender'], as_index=False)['Amount'].sum().sort_values(by = 'Amount', ascending=False)
sns.barplot(x='Gender', y = 'Amount', data= sales)

"""##Age"""

k = sns.countplot(data=data, x='Age Group', hue='Gender') # hue is lable in right top corner and devide in m and f
for bars in k.containers:
  k.bar_label(bars)

"""## State"""

data.columns

sales = data.groupby(['State'], as_index=False)['Orders'].sum().sort_values(by = 'Orders', ascending=False).head(10)
sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(x='State', y = 'Orders', data= sales)

sales = data.groupby(['State'], as_index=False)['Amount'].sum().sort_values(by = 'Amount', ascending=False).head(10)
sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(x='State', y = 'Amount', data= sales)

"""## Marital Status

"""

k = sns.countplot(data=data, x='Marital_Status')
sns.set(rc={'figure.figsize':(5,5)})
for bars in k.containers:
  k.bar_label(bars)

sales = data.groupby(['Marital_Status','Gender'], as_index=False)['Amount'].sum().sort_values(by = 'Amount', ascending=False).head(10)
sns.barplot(x='Marital_Status', y = 'Amount', data= sales, hue='Gender')

"""## Occupation"""

k = sns.countplot(data=data, x='Occupation')
sns.set(rc={'figure.figsize':(30,5)})
for bars in k.containers:
  k.bar_label(bars)

sales = data.groupby(['Occupation'], as_index=False)['Amount'].sum().sort_values(by = 'Amount', ascending=False)
sns.barplot(x='Occupation', y = 'Amount', data= sales)

"""## Product Catagory"""

k = sns.countplot(data=data, x='Product_Category')
sns.set(rc={'figure.figsize':(30,5)})
for bars in k.containers:
  k.bar_label(bars)

sales = data.groupby(['Product_Category'], as_index=False)['Amount'].sum().sort_values(by = 'Amount', ascending=False).head(10)
sns.barplot(x='Product_Category', y = 'Amount', data= sales)

sales = data.groupby(['Product_ID'], as_index=False)['Orders'].sum().sort_values(by = 'Orders', ascending=False).head(10)
sns.barplot(x='Product_ID', y = 'Orders', data= sales)

fig1 , k1 = plt.subplots(figsize=(12,7))
data.groupby('Product_ID')['Orders'].sum().nlargest(10).sort_values(ascending=False).plot(kind='bar')

"""# Conclusion :

Married women age group 26-35 yrs from up, MH, and Karnataka working in IT, Healthcare and avialtion are more likely buy product from food ,clothing and electronics
"""

